name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install and Build
      env:
        AYAME_SIGNALING_KEY: ${{ secrets.AYAME_SIGNALING_KEY }} 
        AYAME_ROOM_NAME: ${{ secrets.AYAME_ROOM_NAME }}
      run: |
        yarn install
        yarn build
        mkdir build
        cp ./*.html ./build/
        mv dist/ ./build/
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
